version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db

  nodeapp:
    build: ./app
    container_name: nodejs_app
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodeapp

volumes:
  mongo_data: